listens:
  - address: "192.168.1.10"
    port: 8443
    tls_ca_cert: "ca.pem"
    tls_cert: "server.pem"
    tls_key: "server-key.pem"
    backends:
      - address: "172.20.123.4"
        port: 443
        scheme: "https"
        skip_verify_tls_cert: false
        tls_ca_cert: "backend-ca.pem"
